matrix:
  include:
    - language: python
      python:
      - '3.6'
      - '3.7'
      - '3.8'
      - '3.9'
      before_install:
        - cd backend/
      install:
        - pip install -r requirements.txt
      script:
        - python -m pytest inv_backend_tests.py
    
    - language: node_js
      node_js:
        - '12'
      before_install:
        - cd frontend/
      install:
        - npm install
      script:
        - sudo npm test
